#13 Fix reversed expander icons on expandable items
croz-ltd/tiller pull request #14
Opened 2023-01-16 08:28 UTC by fbeceic

## Basic information

* Tiller version: 1.0.1
* Module: menu

## Bug description

Expander icon is reversed on mobile view. Arrow up icon is shown when item is not expanded while arrow down icon
is shown when an item is expanded. Icons should be reversed.

### Related issue

Closes #13 

## Checklist

- [x] I have read the project's **CONTRIBUTING** document
- [x] I have checked my code with the project's static analysis tooling
- [x] I have formatted my code with the project's Prettier code-style configuration
- [x] I have checked my code for misspellings
- [x] I have organized my changes in easy-to-follow commits
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added a story to cover my changes
- [x] All new and existing story tests pass

2023-01-16 11:16 UTC, jtomic-croz requested changes

2023-01-16 11:16 UTC, jtomic-croz commented on libs/menu/src/TopNavigation.tsx
> +              {opened ? expanderOpenIcon : expanderCloseIcon}
This seems like the old condition was ok, but icons were reversed. `expanderOpen` should be the one that is shown when user needs to open the dropdown/card/collapse, not when it's already opened

2023-01-16 16:21 UTC, jtomic-croz commented on libs/core/src/Card.tsx
> +  const expanderOpenIcon = useIcon("openExpander", props.expanderOpenIcon, { className: "ml-2", size: 3 });
Can you also rename all the usages to match the icon name?
eg: `const openExpanderIcon = useIcon("openExpander", ...

2023-01-17 13:07 UTC, ivam5 submitted a review, later dismissed

2023-01-18 15:58 UTC, jtomic-croz approved these changes

2023-01-18 15:59 UTC, merged